### ISSUE TITLE
Compilation Time

### ISSUE THREAD

**Issue by Psoke** [klementuel/open62541Tutorial#3]
Hi
Ich komm von youtube, da hatte ich bei einem Video über den NodeSet Compiler die Frage gestellt, wie sich die compilation time verringern lässt da es bei mir immer so 15min gedauert hat mit einer Fehlermeldung über einen overflow in namespace0_generated. Nachdem ich nun nicht in einer VM sondern cleanen install von Ubuntu compile, dauert es noch so 6-7min was aber trotzdem viel mehr ist als im Video, da compiled er instantan. 
Du meintest du hättest den Fehler gefunden und mich hier hin umgeleitet. Ich benutze deine Befehle zum compilen aber es dauert trotzdem immernoch 6-7min. Hast du eine Idee voran das leigen könnte?

**Comment by klementuel** [comment]
Hallo,
Ja das ist ein bissche tricky, hast du schon probiert den reduced namespace zu benutzen bzw. so wie in den YouTube Videos vom Johannes einfach nur mit der einen C Datei?

Wenn das alles nichts hilft und dir zu lange dauert, müsstest duu über eien Cross Compiler gehen zb. wie in diesem Beitrag
https://stackoverflow.com/questions/19162072/how-to-install-the-raspberry-pi-cross-compiler-on-my-linux-host-machine/58559140#58559140
